"""Example design: a USB-C powered ATtiny85 board with a Qwiic I2C port.

It is the toolkit's self-test fixture and a worked example of generating a schematic with tw.sch:

  schematic(hw_dir)   the hierarchical schematic (root + Power + MCU sheets)
  outline_op()        the board outline op (50 x 35 mm, 2 mm corners)
  placement()         where every footprint goes, and why

Parts are from JLC stock (queried 2026-09-26). ATTINY85-20SU is the 208-mil SOIC-8 (5.3 mm body):
it takes Package_SO:SOIC-8_5.3x5.3mm_P1.27mm, not the 3.9 mm SOIC-8 -- the distributor's package
field is what showed it.
"""
from tw.sch import Design, Part, stock


def catalog():
    R, C = stock("Device", "R"), stock("Device", "C")
    return {
        "R5k1": Part(R, "Resistor_SMD:R_0402_1005Metric", "5.1k", "0402WGF5101TCE", "UNI-ROYAL", "C25905"),
        "R1k": Part(R, "Resistor_SMD:R_0402_1005Metric", "1k", "0402WGF1001TCE", "UNI-ROYAL", "C11702"),
        "R4k7": Part(R, "Resistor_SMD:R_0402_1005Metric", "4.7k", "0402WGF4701TCE", "UNI-ROYAL", "C25900"),
        "R10k": Part(R, "Resistor_SMD:R_0402_1005Metric", "10k", "0402WGF1002TCE", "UNI-ROYAL", "C25744"),
        "R68": Part(R, "Resistor_SMD:R_0402_1005Metric", "68R", "0402WGF680JTCE", "UNI-ROYAL", "C25108"),
        "C100n": Part(C, "Capacitor_SMD:C_0402_1005Metric", "100n", "CL05B104KO5NNNC", "Samsung", "C1525"),
        "C10u": Part(C, "Capacitor_SMD:C_0805_2012Metric", "10u 25V", "CL21A106KAYNNNE", "Samsung", "C15850"),
        "C22u": Part(C, "Capacitor_SMD:C_1206_3216Metric", "22u 25V", "CL31A226KAHNNNE", "Samsung", "C12891"),
        "LED_R": Part(stock("Device", "LED"), "LED_SMD:LED_0603_1608Metric", "red", "KT-0603R", "Hubei KENTO", "C2286"),
        "USBC": Part(stock("Connector", "USB_C_Receptacle_USB2.0_16P"),
                     "Connector_USB:USB_C_Receptacle_GCT_USB4105-xx-A_16P_TopMnt_Horizontal", "USB-C", "USB4105-GF-A",
                     "GCT", "C3020560", "https://gct.co/files/drawings/usb4105.pdf"),
        "LDO": Part(stock("Regulator_Linear", "AMS1117-3.3"), "Package_TO_SOT_SMD:SOT-223-3_TabPin2", "AMS1117-3.3",
                    "AMS1117-3.3", "Advanced Monolithic Systems", "C6186"),
        "MCU": Part(stock("MCU_Microchip_ATtiny", "ATtiny85-20S"), "Package_SO:SOIC-8_5.3x5.3mm_P1.27mm", "ATtiny85-20SU",
                    "ATTINY85-20SU", "Microchip", "C31540447"),
        "JST4": Part(stock("Connector_Generic", "Conn_01x04"),
                     "Connector_JST:JST_SH_SM04B-SRSS-TB_1x04-1MP_P1.00mm_Horizontal", "I2C (Qwiic)",
                     "SM04B-SRSS-TB(LF)(SN)", "JST", "C160404"),
    }


def schematic(hw_dir, name="demo", libname="Demo_USB-C_ATtiny"):
    """The schematic, drawn to the conventions professional sheets follow (knowledge: schematic-
    conventions): one function per block, signal flow left to right, supplies up and ground down,
    each decoupling capacitor wired to the pin it serves, nets named in capitals, theme colours only,
    a cover sheet with the contents and general notes, filled title blocks."""
    cat = catalog()
    d = Design(name, libname=libname, title="USB-C ATtiny85 board", company="Tracewright example design",
               comments=("USB-C sink, AMS1117 3.3 V, ATtiny85, Qwiic I2C",
                         "Generated by tw/examples/demo_board.py: edit the script, not the sheets"))
    root = d.root("Cover", paper="A4")
    pw = d.sheet("Power", "power.kicad_sch", "USB-C input and 3.3 V", paper="A4",
                 description="USB-C input (5 V sink), 3.3 V regulator, power LED")
    mc = d.sheet("MCU", "mcu.kicad_sch", "ATtiny85 and I2C", paper="A4",
                 description="ATtiny85, USB data lines, Qwiic I2C port")

    # ------------------------------------------------------------------ cover: blocks, contents, notes
    r = d.builder(root, 0, cat)
    root.text("USB-C ATtiny85 board: USB-C powered ATtiny85 with a Qwiic I2C port.\n"
              "5 V from USB-C (a 5.1k Rd on each CC pin), AMS1117 to 3.3 V for the MCU and the I2C bus.",
              (25.4, 22.86), size=1.27)
    pins = [("USB_D_P", 10.16), ("USB_D_N", 15.24)]
    root.subsheet(pw, (38.1, 40.64), (50.8, 25.4), [(n, "right", o, "bidirectional") for n, o in pins])
    root.subsheet(mc, (132.08, 40.64), (50.8, 25.4), [(n, "left", o, "bidirectional") for n, o in pins])
    for n, _ in pins:
        root.wire(root.sheet_pin_pos(pw, n), root.sheet_pin_pos(mc, n))
    d.contents((25.4, 86.36))
    r.notes((132.08, 86.36), ["Resistors 0402 1 %, capacitors 0402 X7R / X5R, unless noted.",
                              "Capacitor values: capacitance, then the voltage rating where it matters (10u 25V).",
                              "Net names in capitals; _P / _N are the two halves of a differential pair.",
                              "Parts marked DNP are not fitted."])
    r.block(22.86, 121.92, 144.78, 154.94, "MECHANICAL")
    hole = stock("Mechanical", "MountingHole")
    for i in range(4):
        root.add(hole, f"H{i + 1}", "M3", (43.18 + 20.32 * i, 139.7), footprint="MountingHole:MountingHole_3.2mm_M3")
    r.note("M3 mounting holes, 3.5 mm in from each corner", (35.56, 147.32))

    # ------------------------------------------------------------------ Power: USB-C input
    b = d.builder(pw, 0, cat)
    b.block(15.24, 15.24, 116.84, 93.98, "USB-C INPUT (5 V SINK)")
    J = b.ic("USBC", "J", "A4", (50.8, 38.1), ref="J1")
    vb = b.w(J.pin("A4"), (68.58, 38.1))                    # VBUS -> +5V, flagged where power enters
    b.flag((58.42, 38.1))
    b.j((58.42, 38.1))
    b.rail(vb, "+5V")
    for pin, net, x in (("A5", "CC1", 96.52), ("B5", "CC2", 83.82)):
        a = J.pin(pin)                                      # CC pin -> its own 5.1k Rd to ground
        b.w(a, (x, a[1]), (x, 48.26))
        b.lab((55.88, a[1]), net)
        rd = b.two("R5k1", "R", (x, 48.26), "down", ref={"CC1": "R1", "CC2": "R2"}[net])
        b.gnd(rd.pin("2"))
    for pa, pb, net in (("A7", "B7", "USB_D_N"), ("A6", "B6", "USB_D_P")):
        a, c = b.stub(J, pa, 2.54), b.stub(J, pb, 2.54)     # both rows joined right at the receptacle
        b.w(a, c)
        e = b.w(a, (a[0] + 7.62, a[1]))
        b.j(a)
        b.hl(e, net, "r", "bidirectional")
    b.nc(J, "A8")
    b.nc(J, "B8")
    b.pin_gnd(J, "A1", 2.54)
    b.pin_gnd(J, "SH", 2.54)
    b.flag((45.72, 86.36))
    b.gnd((45.72, 86.36))
    b.note("Rd: 5.1k from each CC pin to GND,\nso a USB-C source turns VBUS on.", (78.74, 63.5))
    b.note("A6/B6 and A7/B7 are joined at the\nreceptacle: the plug works either way up.", (58.42, 71.12))

    # ------------------------------------------------------------------ Power: 3.3 V regulator
    b.block(121.92, 15.24, 210.82, 93.98, "3.3 V REGULATOR")
    U = b.ic("LDO", "U", "3", (152.4, 45.72), ref="U1")
    b.pin_cap(U, "3", ["C10u"], "+5V", reach=12.7, pitch=7.62, refs=["C1"])          # input cap at VI
    b.pin_cap(U, "2", ["C22u", "C100n"], "+3V3", reach=5.08, pitch=15.24, refs=["C2", "C3"])
    b.pin_gnd(U, "1", 2.54)
    b.note("C1 at the input. C2 (22u) at the output keeps\nthe AMS1117 stable: it needs >= 22 uF.", (132.08, 68.58))

    # ------------------------------------------------------------------ Power: LED
    b.block(215.9, 15.24, 281.94, 93.98, "POWER LED")
    r3 = b.two("R1k", "R", (236.22, 38.1), "down", ref="R3")
    b.rail(r3.pin("1"), "+3V3")
    d1 = b.two("LED_R", "D", (236.22, 60.96), "up", ref="D1")        # cathode (pin 1) down, anode up
    b.w(r3.pin("2"), d1.pin("2"))
    b.gnd(d1.pin("1"))
    b.note("about 1.3 mA:\n(3.3 V - 2.0 V) / 1k", (243.84, 45.72))

    # ------------------------------------------------------------------ MCU sheet: the ATtiny85
    m = d.builder(mc, 0, cat)
    m.block(15.24, 15.24, 147.32, 96.52, "ATtiny85 MICROCONTROLLER")
    U2 = m.ic("MCU", "U", "8", (60.96, 45.72), ref="U2")
    bx0, by0, bx1, by1 = U2.bbox()                           # fields right of the VCC wire
    U2.ref_at, U2.val_at = (62.23, by0 - 5.08, "left"), (62.23, by0 - 2.54, "left")
    m.pin_cap(U2, "8", ["C100n"], "+3V3", side="left", pitch=15.24, reach=7.62, refs=["C4"])
    m.pin_gnd(U2, "4", 2.54)
    m.pin_lab(U2, "5", "I2C_SDA", 7.62)
    m.pin_lab(U2, "7", "I2C_SCL", 7.62)
    m.nc(U2, "6")
    a = m.stub(U2, "2", 15.24)                               # PB3 -> 68R -> USB_D_N
    m.lab((78.74, a[1]), "PB3_USB_N")
    r7 = m.two("R68", "R", a, "right", ref="R7")
    m.hl(m.w(r7.pin("2"), (r7.pin("2")[0] + 2.54, a[1])), "USB_D_N", "r", "bidirectional")
    p3 = U2.pin("3")                                         # PB4 jogs down, clear of R7 -> 68R -> USB_D_P
    b4 = m.w(p3, (80.01, p3[1]), (80.01, 71.12), (91.44, 71.12))
    m.lab((81.28, 71.12), "PB4_USB_P")
    r6 = m.two("R68", "R", b4, "right", ref="R6")
    m.hl(m.w(r6.pin("2"), (r6.pin("2")[0] + 2.54, 71.12)), "USB_D_P", "r", "bidirectional")
    p1 = U2.pin("1")                                         # RESET: down and out to its pull-up
    rs = m.w(p1, (77.47, p1[1]), (77.47, 83.82), (121.92, 83.82))
    m.lab((82.55, 83.82), "RESET")
    m.pull(rs, "R10k", "+3V3", ref="R4")
    m.note("C4 at U2 pin 8 (VCC).", (22.86, 33.02))
    m.note("68R in series on each\nUSB data line.", (116.84, 62.23))
    m.note("RESET pulled up (10k): the ATtiny85\nruns when nothing drives it.", (81.28, 88.9))

    # ------------------------------------------------------------------ MCU sheet: the Qwiic port
    m.block(177.8, 15.24, 271.78, 96.52, "QWIIC I2C PORT")
    J2 = m.ic("JST4", "J", "1", (254.0, 48.26), rot=0, ref="J2")
    g = m.stub(J2, "1", 2.54)
    m.gnd(g, rot=270)
    v = m.stub(J2, "2", 7.62)
    m.rail(v, "+3V3", rot=90)
    sda = m.w(J2.pin("3"), (228.6, J2.pin("3")[1]))
    scl = m.w(J2.pin("4"), (203.2, J2.pin("4")[1]))
    m.pull((236.22, sda[1]), "R4k7", "+3V3", ref="R8", fields_left=True)
    m.pull((213.36, scl[1]), "R4k7", "+3V3", ref="R9", fields_left=True)
    m.lab(sda, "I2C_SDA", "l")
    m.lab(scl, "I2C_SCL", "l")
    m.note("Qwiic: 1 GND, 2 3V3, 3 SDA, 4 SCL.\nR8, R9: the bus pull-ups (4.7k to 3.3 V).", (203.2, 71.12))
    return d.write(hw_dir)


def outline_op(x0=100.0, y0=100.0, w=50.0, h=35.0, r=2.0):
    return {"op": "outline", "rect": [x0, y0, x0 + w, y0 + h], "radius": r}


def placement(x0=100.0, y0=100.0):
    """Board origin (x0, y0), 50 x 35 mm, everything on the top side."""
    def at(dx, dy, rot=0):
        return {"x": x0 + dx, "y": y0 + dy, "rot": rot, "side": "F"}
    return {
        "J1": at(3.675, 17.5, 270),                     # USB-C: mouth on the left edge
        "R1": at(10.5, 12.0), "R2": at(10.5, 23.0),     # CC pull-downs beside the receptacle
        "C1": at(13.5, 17.5, 90),                       # LDO input cap between connector and LDO
        "U1": at(19.5, 17.5),                           # AMS1117, tab to the right
        "C2": at(27.0, 12.5, 90), "C3": at(27.0, 22.5, 90),
        "R3": at(19.0, 29.0), "D1": at(23.0, 29.0, 180),
        "U2": at(35.5, 17.5),                           # ATtiny85 in the middle
        "C4": at(38.5, 13.0),                           # right above pin 8 (top right of the SOIC)
        "R4": at(31.0, 24.5, 90),
        "R6": at(30.0, 7.0), "R7": at(30.0, 5.0),
        "R8": at(41.5, 12.0, 90), "R9": at(43.5, 12.0, 90),
        "J2": at(46.5, 17.5, 90),                       # Qwiic: mouth at the right edge, MP pads 0.7 mm in
        "H1": at(3.5, 3.5), "H2": at(46.5, 3.5), "H3": at(3.5, 31.5), "H4": at(46.5, 31.5),
    }


def rules():
    """Project design rules (.kicad_dru), each with its reason."""
    return {"USB4105 pegs": """# GCT USB4105 land pattern: the shell pegs sit 0.194 mm from the GND pads (vendor drawing),
# inside the connector's own footprint
(rule "USB4105 pegs"
  (condition "A.Parent == 'J1' && B.Parent == 'J1'")
  (constraint hole_clearance (min 0.19mm)))"""}


def pour_op(x0=100.0, y0=100.0, w=50.0, h=35.0, inset=0.5):
    """GND on both layers; SMD pads join solid, through-hole pads by thermal relief."""
    edge = [[x0 + inset, y0 + inset], [x0 + w - inset, y0 + inset], [x0 + w - inset, y0 + h - inset], [x0 + inset, y0 + h - inset]]
    return {"op": "zone", "net": "GND", "layers": ["F.Cu", "B.Cu"], "polygon": edge, "clearance": 0.25,
            "connect": "tht", "name": "GND pour"}


def hand_routes(x0=100.0, y0=100.0):
    """The USB-C data breakout, laid by hand: the D- pads (B7, A7) sit either side of a D+ pad (A6),
    so D+ joins on top behind the pads and D- drops through two vias and joins on the bottom.
    J1 (rot 270) puts its pad row at x = x0 + 7.355, pads at y = y0 + 17.5 + (pad x in the footprint)."""
    px = x0 + 7.355                   # pad centres
    yc = y0 + 17.5
    y = {"B7": yc - 0.75, "A6": yc - 0.25, "A7": yc + 0.25, "B6": yc + 0.75}
    w, vd, vdr = 0.15, 0.5, 0.3
    vx = px + 1.0
    return [
        {"op": "tracks", "items": [
            # D+ : A6 straight out, B6 out and up to meet it
            {"net": "USB_D_P", "layer": "F.Cu", "a": [px, y["A6"]], "b": [px + 2.2, y["A6"]], "w": w},
            {"net": "USB_D_P", "layer": "F.Cu", "a": [px, y["B6"]], "b": [px + 1.7, y["B6"]], "w": w},
            {"net": "USB_D_P", "layer": "F.Cu", "a": [px + 1.7, y["B6"]], "b": [px + 2.2, y["A7"]], "w": w},
            {"net": "USB_D_P", "layer": "F.Cu", "a": [px + 2.2, y["A7"]], "b": [px + 2.2, y["A6"]], "w": w},
            # D- : both pads to a via each, joined on B.Cu
            {"net": "USB_D_N", "layer": "F.Cu", "a": [px, y["B7"]], "b": [vx, y["B7"]], "w": w},
            {"net": "USB_D_N", "layer": "F.Cu", "a": [px, y["A7"]], "b": [vx, y["A7"]], "w": w},
            {"net": "USB_D_N", "layer": "B.Cu", "a": [vx, y["B7"]], "b": [vx, y["A7"]], "w": 0.2},
        ]},
        {"op": "vias", "items": [{"net": "USB_D_N", "x": vx, "y": y["B7"], "d": vd, "drill": vdr},
                                 {"net": "USB_D_N", "x": vx, "y": y["A7"], "d": vd, "drill": vdr}]},
    ]
